### ISSUE TITLE
Plugin Over right issue

### ISSUE THREAD

**Issue by natr566** [Rengobli/aEssentials#1]
I seem to be having an issue with your plugin Over righting other plugin commands. like i have factions on my server and i do /f in factions is supposed to bring up factions help but with your plugin running it sais The command /f does not exist.

**Comment by Rengobli** [comment]
There is no such command as "/f" in aEssentials.
I am 100% sure that this error is not from my resource. However, does it happen if you un.install aEssentials of your server?

**Comment by natr566** [comment]
im a aware this is not a command used by your plugin but when i uninstall aEssentials it works fine.
its like all plugins that are not registering commands properly like the one the uses /f your plugin overights the command with does not exist message

**Comment by Rengobli** [comment]
Hmmm.. okay I'll look over it

**Comment by natr566** [comment]
So you fixed it then? or you just closed the issue?

**Comment by Rengobli** [comment]
I did not find an issue.
Dunno how this happened to you :/

**Comment by natr566** [comment]
u test your own plugins on a server?
